sudo: required
services:
  - docker

before_install:
  - docker build -t finlaypingpoh/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true finlaypingpoh/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-870830418576"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws-access-key-id
  secret_access_key:
    secure: "$aws-secret-key-id"